name: frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  HTML-Lint-Test:
    name: HTML Lint test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run HTML Lint 
      run: npx linthtml 'frontend/*.html'

    - name: Run JS Lint 
      run: npx eslint frontend/js/*.js

    - name: Run CSS Lint 
      run:  npx stylelint "frontend/css/*.css"

    
